# Configuration de la connexion à PostgreSQL
# Ce fichier est ignoré par Git pour des raisons de sécurité

DB_HOST = "localhost"
DB_PORT = 5432
DB_NAME = "netflix_db"
DB_USER = "postgres"
DB_PASSWORD = "votre_mot_de_passe"
